[color-theme]
name = "Light Pastel Dawn"

[color-theme.base]
white = "#FBFBFB"
black = "#3D3D3D"
grey = "#8C8C8C"
blue = "#92B6F4"
red = "#F4A7A0"
yellow = "#FFF3C6"
orange = "#FFE0A3"
green = "#B7F0A5"
purple = "#D1A3FF"
cyan = "#A3FFFF"
magenta = "#D1A3FF"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$orange"
comment = "#B9D9E6"
constant = "#FFB8D2"
constructor = "$orange"
embedded = "$cyan"
enum = "$orange"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$orange"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$orange"
property = "$red"
"punctuation.delimiter" = "$white"
selfKeyword = "$purple"
string = "#E0F8CF"
"string.escape" = "$cyan"
struct = "$orange"
structure = "$orange"
symbol = "$orange"
tag = "$blue"
"text.reference" = "$orange"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$orange"
"type.builtin" = "$orange"
typeAlias = "$orange"
variable = "#C4E3FF"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#454954"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#4D596655"
"completion_lens.foreground" = "#B0B0C8"
"editor.background" = "$black"
"editor.caret" = "#F8C8DC"
"editor.current_line" = "#404347"
"editor.dim" = "#B0B0C8"
"editor.drag_drop_background" = "#92B6F455"
"editor.drag_drop_tab_background" = "#3E414855"
"editor.focus" = "#F0F0E8"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#F4A7A055"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#B0B0C855"
"error_lens.other.foreground" = "#B0B0C8"
"error_lens.warning.background" = "#FFF3C655"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#353739"
"inlay_hint.background" = "#404449"
"inlay_hint.foreground" = "#D0D0E0"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#3B3D41"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "$grey"
"lapce.plugin.author" = "$blue"
"lapce.plugin.description" = "#E0E0E0"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "#B7F0A5"
"lapce.remote.connecting" = "#FFE0A3"
"lapce.remote.disconnected" = "#F4A7A0"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$green"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#F8C8DC"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#F8C8DC"
"lapce.tab.separator" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#B1B1B1"
"palette.background" = "$black"
"palette.current.background" = "#4D596655"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#4D596655"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#B0B0C8"
"panel.foreground" = "$white"
"panel.foreground.dim" = "$purple"
"panel.hovered.background" = "#4D596B56"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#B0B0C8"
"source_control.added" = "#B7F0A532"
"source_control.modified" = "#92B6F432"
"source_control.removed" = "#F4A7A032"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#949494"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#FBFBFB"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
