[color-theme]
name = 'Lively Pastel'

[color-theme.base]
black = '#292828'
blue = '#61afef'
cyan = '#56b6c2'
green = '#a1cd81'
grey = '#757575'
magenta = '#9B7AA6'
orange = '#e5c07b'
purple = '#b871cc'
red = '#f57883'
white = '#e9e0c9'
yellow = '#d4b274'

[color-theme.syntax]
attribute = '$yellow'
builtinType = '$orange'
comment = '#757575'
constant = '#B7E1F4'
constructor = '$oraneg'
embedded = '$cyan'
enum = '$orange'
enum-member = '$red'
enumMember = '$red'
escape = '$cyan'
field = '$red'
function = '$blue'
"function.method" = '$blue'
interface = '$orange'
keyword = '$orange'
"keyword.control" = '#f7cad5'
method = '$blue'
number = '$orange'
property = '$red'
"punctuation.delimiter" = '#f7cad5'
selfKeyword = '#f7cad5'
string = '#a1cd81'
"string.escape" = '$cyan'
struct = '$orange'
structure = '$orange'
symbol = '$orange'
tag = '$blue'
"text.reference" = '$orange'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$orange'
"type.builtin" = '$orange'
typeAlias = '$orange'
variable = '#B7E1F4'
"variable.other.member" = '$green'

[color-theme.ui]
"activity.background" = '#3a3838'
"activity.current" = '$black'
"completion.background" = '$black'
"completion.current" = '#3E4A5955'
"completion_lens.foreground" = '#A0A0B8'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C7566'
"editor.background" = '$black'
"editor.caret" = '#ffdfe6'
"editor.current_line" = '#3a3838'
"editor.dim" = '#A0A0B8'
"editor.drag_drop_background" = '#80A4ED55'
"editor.drag_drop_tab_background" = '#2E313855'
"editor.focus" = '#E8E8E0'
"editor.foreground" = '$white'
"editor.indent_guide" = '$grey'
"editor.link" = '$cyan'
"editor.selection" = '$grey'
"editor.sticky_header_background" = '$black'
"editor.visible_whitespace" = '$grey'
"error_lens.error.background" = ''
"error_lens.error.foreground" = ''
"error_lens.other.background" = ''
"error_lens.other.foreground" = ''
"error_lens.warning.background" = ''
"error_lens.warning.foreground" = ''
"hover.background" = '#2D2F33'
"inlay_hint.background" = '#35393D'
"inlay_hint.foreground" = '#C0C0D0'
"lapce.border" = '$black'
"lapce.button.primary.background" = '$green'
"lapce.button.primary.foreground" = '$black'
"lapce.dropdown_shadow" = ''
"lapce.error" = '#f29b9b'
"lapce.icon.active" = '$white'
"lapce.icon.inactive" = '$grey'
"lapce.plugin.author" = '$blue'
"lapce.plugin.description" = '#D0D0D0'
"lapce.plugin.name" = '$white'
"lapce.remote.connected" = '#8ABD8A'
"lapce.remote.connecting" = '#B18A73'
"lapce.remote.disconnected" = '#B18782'
"lapce.remote.icon" = '$black'
"lapce.remote.local" = '$green'
"lapce.scroll_bar" = '#303030'
"lapce.tab.active.background" = '$black'
"lapce.tab.active.foreground" = '$white'
"lapce.tab.active.underline" = '#F8C8DC'
"lapce.tab.inactive.background" = '$black'
"lapce.tab.inactive.foreground" = '$white'
"lapce.tab.inactive.underline" = '#F8C8DC'
"lapce.tab.separator" = '$grey'
"lapce.warn" = '$yellow' 
"markdown.blockquote" = '#A8A8A8'
"palette.background" = '##00000075'
"palette.current.background" = '#3a3838'
"palette.current.foreground" = '$white'
"palette.foreground" = '$white'
"panel.background" = '#232222'
"panel.current.background" = '#3a3838'
"panel.current.foreground" = '$white'
"panel.current.foreground.dim" = '#A0A0B8'
"panel.foreground" = '$white'
"panel.foreground.dim" = '$purple'
"panel.hovered.active.background" = '#5C6370'
"panel.hovered.background" = '#3a3838'
"panel.hovered.foreground" = '$white'
"panel.hovered.foreground.dim" = '#A0A0B8'
"source_control.added" = '#8ABD8A32'
"source_control.modified" = '#6A8FB132'
"source_control.removed" = '#B1878232'
"status.background" = '$black'
"status.foreground" = '$white'
"status.modal.insert.background" = '#f7c7c6'
"status.modal.insert.foreground" = '$black'
"status.modal.normal.background" = '#B7E1F4'
"status.modal.normal.foreground" = '$black'
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$black'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$black'
"terminal.background" = '$black'
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#757575'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '#F8F8F2'
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '#F8C8DC'
"terminal.cyan" = '$cyan'
"terminal.foreground" = '$white'
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$white'
"terminal.yellow" = '$yellow'

[ui]
drop-shadow-width = 0
font-family = ""
font-size = 13
header-height = 15
hover-font-family = ''
hover-font-size = 0
icon-size = 0
list-line-height = 25
preview-editor-width = 0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
trim-search-results-whitespace = true
