[color-theme]
name = "Pastel Pale"

[color-theme.base]
white = "#F7F7F7"
black = "#383838"
grey = "#949494"
blue = "#AED6F1"
red = "#F5B7B1"
yellow = "#FDEBD0"
orange = "#FAD7A0"
green = "#ABEBC6"
purple = "#D7BDE2"
cyan = "#AED6F1"
magenta = "#F5B7B1"

[color-theme.syntax]
attribute = "$cyan"
builtinType = "$cyan"
comment = "#D1C4E9"
constant = "$magenta"
constructor = "$cyan"
embedded = "$blue"
enum = "$cyan"
enum-member = "$magenta"
enumMember = "$magenta"
escape = "$blue"
field = "$magenta"
function = "$blue"
"function.method" = "$blue"
interface = "$cyan"
keyword = "$magenta"
"keyword.control" = "$magenta"
method = "$blue"
number = "$cyan"
property = "$magenta"
"punctuation.delimiter" = "$white"
selfKeyword = "$magenta"
string = "#FADBD8"
"string.escape" = "$blue"
struct = "$cyan"
structure = "$cyan"
symbol = "$cyan"
tag = "$blue"
"text.reference" = "$cyan"
"text.title" = "$orange"
"text.uri" = "$blue"
type = "$cyan"
"type.builtin" = "$cyan"
typeAlias = "$cyan"
variable = "#E8DAEF"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#424949"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#5499C755"
"completion_lens.foreground" = "#CACFD2"
"editor.background" = "$black"
"editor.caret" = "#F8C8DC"
"editor.current_line" = "#424949"
"editor.dim" = "#CACFD2"
"editor.drag_drop_background" = "#AED6F155"
"editor.drag_drop_tab_background" = "#38383855"
"editor.focus" = "#FEF9E7"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "#D6EAF855"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#F1948A55"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#D5D8DC55"
"error_lens.other.foreground" = "#ABB2B9"
"error_lens.warning.background" = "#F9E79F55"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#424949"
"inlay_hint.background" = "#424949"
"inlay_hint.foreground" = "#D5D8DC"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#424949"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "$grey"
"lapce.plugin.author" = "$blue"
"lapce.plugin.description" = "#E5E7E9"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "#82E0AA"
"lapce.remote.connecting" = "#F7DC6F"
"lapce.remote.disconnected" = "#E74C3C"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$green"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#F8C8DC"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#F8C8DC"
"lapce.tab.separator" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#D5D8DC"
"palette.background" = "$black"
"palette.current.background" = "#5499C755"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#5499C755"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#CACFD2"
"panel.foreground" = "$white"
"panel.foreground.dim" = "$purple"
"panel.hovered.background" = "#5499C755"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#CACFD2"
"source_control.added" = "#82E0AA55"
"source_control.modified" = "#AED6F155"
"source_control.removed" = "#F1948A55"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#AAB7B8"
"terminal.bright_blue" = "#AED6F1"
"terminal.bright_cyan" = "#AED6F1"
"terminal.bright_green" = "#ABEBC6"
"terminal.bright_magenta" = "#F5B7B1"
"terminal.bright_red" = "#F5B7B1"
"terminal.bright_white" = "#FBFBFB"
"terminal.bright_yellow" = "#FDEBD0"
"terminal.cursor" = "$white"
"terminal.cyan" = "#AED6F1"
"terminal.foreground" = "$white"
"terminal.green" = "#ABEBC6"
"terminal.magenta" = "#F5B7B1"
"terminal.red" = "#F5B7B1"
"terminal.white" = "$white"
"terminal.yellow" = "#FDEBD0"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
