[color-theme]
name = "Vibrant Pastel"

[color-theme.base]
white = "#F8F8F2"
black = "#2B2B2B"
grey = "#676767"
blue = "#80A4ED"
red = "#EF8A82"
yellow = "#FAE3B0"
orange = "#FDC88B"
green = "#A4E786"
purple = "#C792EA"
cyan = "#89DDFF"
magenta = "#C792EA"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$orange"
comment = "#B2CCD6"
constant = "#FFA7C4"
constructor = "$orange"
embedded = "$cyan"
enum = "$orange"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$orange"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$orange"
property = "$red"
"punctuation.delimiter" = "$white"
selfKeyword = "$purple"
string = "#D3E7A7"
"string.escape" = "$cyan"
struct = "$orange"
structure = "$orange"
symbol = "$orange"
tag = "$blue"
"text.reference" = "$orange"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$orange"
"type.builtin" = "$orange"
typeAlias = "$orange"
variable = "#B7E1F4"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#323842"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#3E4A5955"
"completion_lens.foreground" = "#A0A0B8"
"editor.background" = "$black"
"editor.caret" = "#F8C8DC"
"editor.current_line" = "#35383D"
"editor.dim" = "#A0A0B8"
"editor.drag_drop_background" = "#80A4ED55"
"editor.drag_drop_tab_background" = "#2E313855"
"editor.focus" = "#E8E8E0"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#EF8A8255"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#A0A0B855"
"error_lens.other.foreground" = "#A0A0B8"
"error_lens.warning.background" = "#FAE3B055"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#2D2F33"
"inlay_hint.background" = "#35393D"
"inlay_hint.foreground" = "#C0C0D0"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#292B2F"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "$grey"
"lapce.plugin.author" = "$blue"
"lapce.plugin.description" = "#D0D0D0"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "#A4E786"
"lapce.remote.connecting" = "#FDC88B"
"lapce.remote.disconnected" = "#EF8A82"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$green"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#F8C8DC"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#F8C8DC"
"lapce.tab.separator" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#A8A8A8"
"palette.background" = "$black"
"palette.current.background" = "#3E4A5955"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#3E4A5955"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#A0A0B8"
"panel.foreground" = "$white"
"panel.foreground.dim" = "$purple"
"panel.hovered.background" = "#3E4A5B56"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#A0A0B8"
"source_control.added" = "#A4E78632"
"source_control.modified" = "#80A4ED32"
"source_control.removed" = "#EF8A8232"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#757575"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#F8F8F2"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
