[color-theme]
name = "Vivid Pastel Dream"

[color-theme.base]
white = "#FFFFFF"
black = "#292D3E"
grey = "#626880"
blue = "#82AAFF"
red = "#FF5370"
yellow = "#FFCB6B"
orange = "#F78C6C"
green = "#C3E88D"
purple = "#C792EA"
cyan = "#89DDFF"
magenta = "#FF5370"

[color-theme.syntax]
attribute = "$cyan"
builtinType = "$cyan"
comment = "#B2CCD6"
constant = "$magenta"
constructor = "$cyan"
embedded = "$blue"
enum = "$cyan"
enum-member = "$magenta"
enumMember = "$magenta"
escape = "$blue"
field = "$magenta"
function = "$blue"
"function.method" = "$blue"
interface = "$cyan"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$cyan"
property = "$magenta"
"punctuation.delimiter" = "$white"
selfKeyword = "$purple"
string = "#FADBD8"
"string.escape" = "$blue"
struct = "$cyan"
structure = "$cyan"
symbol = "$cyan"
tag = "$blue"
"text.reference" = "$cyan"
"text.title" = "$orange"
"text.uri" = "$blue"
type = "$cyan"
"type.builtin" = "$cyan"
typeAlias = "$cyan"
variable = "#EAD9FA"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#2E3440"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#4C566A"
"completion_lens.foreground" = "#D8DEE9"
"editor.background" = "#292D3E"
"editor.caret" = "#F8C8DC"
"editor.current_line" = "#32374D"
"editor.dim" = "#D8DEE9"
"editor.drag_drop_background" = "#82AAFF55"
"editor.drag_drop_tab_background" = "#292D3E55"
"editor.focus" = "#ECEFF4"
"editor.foreground" = "$white"
"editor.indent_guide" = "#4C566A"
"editor.link" = "$blue"
"editor.selection" = "#4C566A"
"editor.sticky_header_background" = "#292D3E"
"editor.visible_whitespace" = "#4C566A"
"error_lens.error.background" = "#BF616A55"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#D8DEE955"
"error_lens.other.foreground" = "#ECEFF4"
"error_lens.warning.background" = "#EBCB8B55"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#3B4252"
"inlay_hint.background" = "#3B4252"
"inlay_hint.foreground" = "#E5E9F0"
"lapce.border" = "#4C566A"
"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#3B4252"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "$grey"
"lapce.plugin.author" = "$blue"
"lapce.plugin.description" = "#E5E9F0"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "#A3BE8C"
"lapce.remote.connecting" = "#D08770"
"lapce.remote.disconnected" = "#BF616A"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$green"
"lapce.scroll_bar" = "#4C566A"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#F8C8DC"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#F8C8DC"
"lapce.tab.separator" = "#4C566A"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#ECEFF4"
"palette.background" = "$black"
"palette.current.background" = "#4C566A"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#4C566A"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#D8DEE9"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#B48EAD"
"panel.hovered.background" = "#4C566A"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#D8DEE9"
"source_control.added" = "#A3BE8C55"
"source_control.modified" = "#81A1C155"
"source_control.removed" = "#BF616A55"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#4C566A"
"terminal.bright_blue" = "#81A1C1"
"terminal.bright_cyan" = "#88C0D0"
"terminal.bright_green" = "#A3BE8C"
"terminal.bright_magenta" = "#B48EAD"
"terminal.bright_red" = "#BF616A"
"terminal.bright_white" = "#ECEFF4"
"terminal.bright_yellow" = "#EBCB8B"
"terminal.cursor" = "$white"
"terminal.cyan" = "#88C0D0"
"terminal.foreground" = "$white"
"terminal.green" = "#A3BE8C"
"terminal.magenta" = "#B48EAD"
"terminal.red" = "#BF616A"
"terminal.white" = "$white"
"terminal.yellow" = "#EBCB8B"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
